#environments:
#    dev:
#        url: http://localhost:9000
#        name: Developer Setup
#    prod:
#        url: http://foo.bar.com
#        name: My Cool App
server:
    port: 9000
    context-path: /my-app

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/boot
        username: root
        password: neo
        driverClassName: com.mysql.jdbc.Driver
# Specify the DBMS
    jpa:
        database: MYSQL
        show-sql: true
# Hibernate ddl auto (create, create-drop, update)
        hibernate:
            ddl-auto: update
# Naming strategy
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
# stripped before adding them to the entity manager)
        properties:
            hibernate:
              dialect: org.hibernate.dialect.MySQL5Dialect
    mail:
        host: email-smtp.us-east-1.amazonaws.com
        port: 25
        username: AKIAINKETU3A7BWQ5IZA
        password: AqUjelRr2Fc1ukdi0R/S3PlO1wT2Zkr36bs1BGDKHbIW
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 180000
                    timeout: 250000
                    starttls:
                        enable: true